### ISSUE TITLE
Support CSV

### ISSUE THREAD

**Issue by rantahar** [digitraceslab/niimpy#11]
Support passing a list of CSV files to the __init__() function.

Could work like this:
 * check if a list of filenames is given. If so, read each file.
 * if the file is a csv file, turn it into a dataframe
 * if the file is an sqlite databases, create a dataframe for each table

**Comment by rkdarst** [comment]
We now have CSV support: https://niimpy.readthedocs.io/en/latest/input-formats/

The first of those points, "list of files", isn't handled.  If it is CSV then it is one file -> one dataframe.  Looking at some more of the processors, this makes interesting questions because some of them combine data from multiple sources.  With a database, you can give one database and it can semi-automatically extract different types of data from it.
