### ISSUE TITLE
data.hourly() is not working properly.

### ISSUE THREAD

**Issue by arc1909** [digitraceslab/niimpy#29]
Upon using data.hourly() function on mmm-bpd-all database with ‘AwareAccelerometer’ as table and ‘RVjtsqp3YdQY’ as user, the function throws an error “AmbiguousTimeError: Cannot infer dst time from 2020-10-25 03:00:00, try using the 'ambiguous' argument”. This is happening for many other users as well.

**Comment by rkdarst** [comment]
I started a branch allowing specifying timezones, which shouldn't affect this but is likely important to fix first.

This problem comes because data is aggregated inside of sqlite3, which is not timezone-aware, and gives the ambiguous time (it occurs twice on that day).  I could fix it, but since the database setup shouldn't be used anymore, maybe its not worth fixing.  I would recommend changing any uses of this to something else.

Does it work if you aggregate hourly using the dataframe-based system?  When you think about it, this is an interesting question, one which has no simple answer: an hour occurs twice that day so what does hourly data mean - there will be twice as much then.  This requires a real scientific choice.

**Comment by amirzia** [comment]
This exception happens when pandas want to convert a raw timestamp to a timezone-aware format and a timestamp lies in the middle of Daylight Saving Time (DST).

According to [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tz_localize.html):
> When clocks moved backward due to DST, ambiguous times may arise. For example in Central European Time (UTC+01), when going from 03:00 DST to 02:00 non-DST, 02:30:00 local time occurs both at 00:30:00 UTC and at 01:30:00 UTC. In such a situation, the ambiguous parameter dictates how ambiguous times should be handled.

One solution is to set `ambiguous` to `False` or `True` but I'm not sure which is more reasonable.
